name: vistext
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.9
  - datasets=2.10.1
  - evaluate=0.4.0
  - gensim=4.3.0
  - h5py
  - nltk=3.7
  - numpy=1.22.3
  - pandas
  - pytorch=1.10.2
  - pyyaml
  - sacrebleu=2.0.0
  - scipy=1.7.3
  - sentencepiece=>0.1.95
  - tokenizers=0.11.4
  - torchvision
  - transformers=4.24.0
  - pip
  - pip:
    - rouge_score
    - pot==0.9.0
    - git+https://github.com/google-research/bleurt.git@cebe7e6f996b40910cfaa520a63db47807e3bf5c